#!/bin/bash
#
# Copyright (c) 2024 Evgeny Sinelnikov <sin@altlinux.org>
#
# Disks diagnostic tool
#
# SPDX-License-Identifier: GPL-2.0-or-later
#

#trap 'echo "# $BASH_COMMAND";read' DEBUG

set -euo pipefail

. shell-getopt

PROG="${0##*/}"
PROG_VERSION='0.0.1'

cmd="run"
global_retval=0

disks=""

print_version()
{
	cat <<EOF
$PROG version $PROG_VERSION
Written by Evgeny Sinelnikov <sin@altlinux.org>

Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
EOF
	exit
}

show_usage()
{
	cat <<EOF
$PROG - disks diagnostic tool.

Usage: $PROG [options] [<diagnostic-task>]

Options:
  -l, --list                list of diagnostic tasks;
  -V, --version             print program version and exit;
  -h, --help                show this text and exit.

Report bugs to https://bugzilla.altlinux.org/

EOF
	exit
}

TEMP=$(getopt -n "$PROG" -o "l,V,h" -l "list,version,help" -- "$@") || show_usage
eval set -- "$TEMP"

while :; do
	case "$1" in
		--) shift; break
			;;
		-l|--list) cmd="list";
			;;
		-V|--version) print_version
			;;
		-h|--help) show_usage
			;;
		*) fatal "Unrecognized option: $1"
			;;
	esac
	shift
done

task_list="$*" #тут он начинает все вызывать

task_show()
{
	local func="$1"

	echo "$func"
}

task_run()
{
	local retval=126
	local func="$1"
	if test -n "$task_list"; then
		echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" ||
			return 0
	fi
	$func && retval=0 || retval="$?"
	test $retval = 0 || global_retval=1
	return $retval
}

task()
{
	local task="$1"
	case "$cmd" in
		list) task_show "$task"
			;; 
		run)
		if test -z "$task_list" || grep "$task" <<< "$task_list"; then
			task_run "$task" && echo "[DONE]: $task" || echo "[FAIL]: $task"
		fi
			;;
		*) fatal "Unrecognized command: $cmd"
			;;
	esac
}

#пофиксить вывод результатов теста -DONE
#Пройтись по выводу приложения

find()
{
	local retval=0
	echo find '('$1')'
	grep " -d"  <<< $1 || retval=1
	echo retval == $retval
	return $retval
}

get_disk()
{
	local retval=0
	local std_out_disk
	std_out_disk=$(smartctl --scan)
	disks=$(echo "$std_out_disk" | grep -E -o '/dev/[^[:space:],]+' | sort | uniq)
	return $retval
}

is_disks()
{
	local retval=0
	#printf "\n"
	#echo Test - is_disks
	echo ================================
	lsblk || retval=1
	echo ================================
	return $retval
}

is_adout_disk()
{
	local retval=0
	echo ================================
	get_disk || retval=1
	for disk in $disks; do
		echo Disk: $disk
        smartctl -i $disk || retval=1
	done
	echo ================================
	return $retval
}

#Проверка включенного SMART
#	Если не включен, то на всех тестах вывести предупреждение, что смарт не включен.
check_support_smart()
{
	local retval=0
	echo ================================
	get_disk || retval=1
	for disk in $disks; do
		echo Disk: $disk
		local disk_info
		disk_info=$(smartctl --info $disk)
		#Добавить ворнинг если есть поддержка, но не включен
		grep 'SMART support is:' <<< $disk_info || retval=1
		if [ $retval -eq 1 ]
			then
			echo S.M.A.R.T. is not supported on $disk
		fi
	done
	echo ================================
	return $retval
}

is_about_disk_status()
{
	local retval=0
	echo ================================
	get_disk || retval=1
	for disk in $disks; do
		echo Disk: $disk
		smartctl -A "$disk" || retval=1
	done
	echo ================================
	return $retval
}

is_disk_health()
{
	local retval=0
	echo ================================
	get_disk || retval=1
	for disk in $disks; do
		echo Disk: $disk
		smartctl -H $disk | grep PASSED || retval=1
	done
	echo ================================
	return $retval
}

#Заготова для теста
short_test_smartctl()
{
	local retval=0
	echo ================================
	get_disk
	for disk in $disks; do
		echo Disk: $disk
		smartctl -t short $disk || retval=1
		#добавить время через которое надо запустить...
		#добавить тест, который будет отдельно считывать selftest, чтоб и анализировать его. А тут напишем "запустите через N минут"
		smartctl -l selftest $disk
	done
	echo ================================
	return $retval
}

task is_disks
task is_adout_disk
task check_support_smart
task is_about_disk_status
task is_disk_health
task short_test_smartctl

exit "$global_retval"
